# Generated by Django 3.1.6 on 2021-02-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
