# Generated by Django 3.1.6 on 2021-02-26 01:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_ad_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='test',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
