# Generated by Django 3.1.6 on 2021-02-26 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_ad_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='test',
        ),
    ]
